### ISSUE TITLE
Bilder in Newsfolder sind nicht bündig.

### ISSUE THREAD

**Issue by elioschmutz** [OneGov/plonetheme.onegovbear#112]
![bildschirmfoto 2016-02-02 um 18 24 43](https://cloud.githubusercontent.com/assets/557005/12757908/51cf8294-c9da-11e5-948a-2428b7c6e6f0.png)

**Comment by elioschmutz** [comment]
Der Anrisstext nach dem Bild ist je nach Bildgrösse verschieden eingerückt.
- [ ] Anrisstext immer auf gleicher Linie ausrichten.

**Comment by bierik** [comment]
Das Bild muss grösser uploaded werden da es nur runterskaliert wird. Dies verhindert, dass das Bild verzerrt oder verpixelt.
