### ISSUE TITLE
Fixe höhe für .masthead

### ISSUE THREAD

**Issue by elioschmutz** [OneGov/plonetheme.onegovbear#118]
In gewissen Seiten möchten wir den Loginbutton deaktivieren. Da nun keine Links mehr im Header vorhanden sind, wird der blaue Balken (.masthead) nicht mehr angezeigt.

Der Balken sollte eine höhe bekommen, damit dieser auch ohne Links korrekt angezeigt wird.
- [ ] Fixe höhe für .masthead

**Comment by bierik** [comment]
Moved to https://github.com/4teamwork/plonetheme.blueberry/issues/12
